# Generated by Django 4.0.4 on 2022-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('turno', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('turno', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
    ]
